export default{
    path:'/movie',
    component:() => import('@/views/Movie'),
    meta:{
        keepAlive:true
    },
    children:[
        {
            path:'city',
            component:()=>import('@/components/City'),
            meta:{
                keepAlive:true
            }
        },
        {
            path:'comingSoon',
            component:()=>import('@/components/ComingSoon'),
            meta:{
                keepAlive:true
            }
        },
        {
            path:'nowPlaying',
            component:()=>import('@/components/NowPlaying'),
            meta:{
                keepAlive:true
            }
        },
        {
            path:'detail/1/:movieId',
            components:{
                default:()=>import('@/components/NowPlaying'),
                detail:()=>import('@/views/Movie/detail')
            },
            props:{
                detail:true
            }
        },
        {
            path:'detail/2/:movieId',
            components:{
                default:()=>import('@/components/ComingSoon'),
                detail:()=>import('@/views/Movie/detail')
            },
            props:{
                detail:true
            }
        },
        {
            path:'search',
            component:()=>import('@/components/Search')
        }
    ]
}